"""
Mirror Evidence Engine (MEE)

Transforms raw trading metrics into human-readable evidence.

Every recommendation generated by TradeMirror must be backed
by objective evidence extracted from the trader's own history.
"""

from typing import Dict, Any


def generate_evidence(metrics: Dict[str, Any]) -> Dict[str, str]:

    win_rate = metrics.get("win_rate", 0)
    profit_factor = metrics.get("profit_factor", 0)
    total_trades = metrics.get("total_trades", 0)
    best_asset = metrics.get("best_asset", "Unknown")

    evidence = {

        "asset_reason":
            f"Your highest historical performance has been achieved trading {best_asset}.",

        "consistency_reason":
            f"Current analysis is based on {total_trades} completed trades.",

        "edge_reason":
            f"Your current Profit Factor is {profit_factor:.2f}.",

        "winrate_reason":
            f"Your historical Win Rate is {win_rate:.2f}%."

    }

    return evidence
